server:
  port: 8082
spring:
  application:
    name: microservice-consumer
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 8.131.103.29:8848
        file-extension: yaml
        refreshable-dataids: false
  datasource:
    url: jdbc:mysql://8.131.103.29:3306/wyc_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 0711Ch!@#
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
